export const sampledata = [
  {
    merek: "Toyota",
    detail: [
      {
        detail_merek: "AGYA",
        detail_spek: [
          {
            tahun: "2017",
            tipe: "E",
            mesin: "1000",
            transmisi: "Manual",
            harga: 70000000,
          },
          {
            tahun: "2017",
            tipe: "E",
            mesin: "1200",
            transmisi: "Manual",
            harga: 85000000,
          },
          {
            tahun: "2017",
            tipe: "E",
            mesin: "1000",
            transmisi: "Automatic",
            harga: 75000000,
          },
          {
            tahun: "2017",
            tipe: "E",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 90000000,
          },
          {
            tahun: "2017",
            tipe: "G",
            mesin: "1000",
            transmisi: "Manual",
            harga: 80000000,
          },
          {
            tahun: "2017",
            tipe: "G",
            mesin: "1200",
            transmisi: "Manual",
            harga: 95000000,
          },
          {
            tahun: "2017",
            tipe: "G",
            mesin: "1000",
            transmisi: "Automatic",
            harga: 85000000,
          },
          {
            tahun: "2017",
            tipe: "G",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 100000000,
          },
          {
            tahun: "2017",
            tipe: "TRD Sportivo",
            mesin: "1000",
            transmisi: "Manual",
            harga: 90000000,
          },
          {
            tahun: "2017",
            tipe: "TRD Sportivo",
            mesin: "1200",
            transmisi: "Manual",
            harga: 105000000,
          },
          {
            tahun: "2017",
            tipe: "TRD Sportivo",
            mesin: "1000",
            transmisi: "Automatic",
            harga: 95000000,
          },
          {
            tahun: "2017",
            tipe: "TRD Sportivo",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 110000000,
          },
          {
            tahun: "2018",
            tipe: "E",
            mesin: "1000",
            transmisi: "Manual",
            harga: 80000000,
          },
          {
            tahun: "2018",
            tipe: "E",
            mesin: "1000",
            transmisi: "Automatic",
            harga: 85000000,
          },
          {
            tahun: "2018",
            tipe: "G",
            mesin: "1000",
            transmisi: "Manual",
            harga: 90000000,
          },
          {
            tahun: "2018",
            tipe: "G",
            mesin: "1200",
            transmisi: "Manual",
            harga: 105000000,
          },
          {
            tahun: "2018",
            tipe: "G",
            mesin: "1000",
            transmisi: "Automatic",
            harga: 95000000,
          },
          {
            tahun: "2018",
            tipe: "G",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 110000000,
          },
          {
            tahun: "2018",
            tipe: "TRD Sportivo",
            mesin: "1000",
            transmisi: "Manual",
            harga: 95000000,
          },
          {
            tahun: "2018",
            tipe: "TRD Sportivo",
            mesin: "1200",
            transmisi: "Manual",
            harga: 110000000,
          },
          {
            tahun: "2018",
            tipe: "TRD Sportivo",
            mesin: "1000",
            transmisi: "Automatic",
            harga: 100000000,
          },
          {
            tahun: "2018",
            tipe: "TRD Sportivo",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 115000000,
          },
          {
            tahun: "2019",
            tipe: "G",
            mesin: "1000",
            transmisi: "Manual",
            harga: 95000000,
          },
          {
            tahun: "2019",
            tipe: "G",
            mesin: "1200",
            transmisi: "Manual",
            harga: 110000000,
          },
          {
            tahun: "2019",
            tipe: "G",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 115000000,
          },
          {
            tahun: "2019",
            tipe: "G TRD",
            mesin: "1200",
            transmisi: "Manual",
            harga: 120000000,
          },
          {
            tahun: "2019",
            tipe: "G TRD",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 125000000,
          },
        ],
      },
      {
        detail_merek: "AVANZA",
        detail_spek: [
          {
            tahun: "2017",
            tipe: "E",
            mesin: "1300",
            transmisi: "Manual",
            harga: 115000000,
          },
          {
            tahun: "2017",
            tipe: "E",
            mesin: "1300",
            transmisi: "Automatic",
            harga: 120000000,
          },
          {
            tahun: "2017",
            tipe: "G",
            mesin: "1300",
            transmisi: "Manual",
            harga: 125000000,
          },
          {
            tahun: "2017",
            tipe: "G",
            mesin: "1300",
            transmisi: "Automatic",
            harga: 130000000,
          },
          {
            tahun: "2017",
            tipe: "G",
            mesin: "1500",
            transmisi: "Manual",
            harga: 135000000,
          },
          {
            tahun: "2017",
            tipe: "G",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 140000000,
          },
          {
            tahun: "2017",
            tipe: "VELOZ",
            mesin: "1500",
            transmisi: "Manual",
            harga: 145000000,
          },
          {
            tahun: "2017",
            tipe: "VELOZ",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 150000000,
          },
          {
            tahun: "2018",
            tipe: "E",
            mesin: "1300",
            transmisi: "Manual",
            harga: 120000000,
          },
          {
            tahun: "2018",
            tipe: "E",
            mesin: "1300",
            transmisi: "Automatic",
            harga: 125000000,
          },
          {
            tahun: "2018",
            tipe: "G",
            mesin: "1300",
            transmisi: "Manual",
            harga: 130000000,
          },
          {
            tahun: "2018",
            tipe: "G",
            mesin: "1300",
            transmisi: "Automatic",
            harga: 135000000,
          },
          {
            tahun: "2018",
            tipe: "G",
            mesin: "1500",
            transmisi: "Manual",
            harga: 140000000,
          },
          {
            tahun: "2018",
            tipe: "G",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 145000000,
          },
          {
            tahun: "2018",
            tipe: "VELOZ",
            mesin: "1500",
            transmisi: "Manual",
            harga: 150000000,
          },
          {
            tahun: "2018",
            tipe: "VELOZ",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 155000000,
          },
          {
            tahun: "2019",
            tipe: "E",
            mesin: "1300",
            transmisi: "Manual",
            harga: 125000000,
          },
          {
            tahun: "2019",
            tipe: "E",
            mesin: "1300",
            transmisi: "Automatic",
            harga: 130000000,
          },
          {
            tahun: "2019",
            tipe: "G",
            mesin: "1300",
            transmisi: "Manual",
            harga: 135000000,
          },
          {
            tahun: "2019",
            tipe: "G",
            mesin: "1300",
            transmisi: "Automatic",
            harga: 140000000,
          },
          {
            tahun: "2019",
            tipe: "G",
            mesin: "1500",
            transmisi: "Manual",
            harga: 145000000,
          },
          {
            tahun: "2019",
            tipe: "G",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 150000000,
          },
          {
            tahun: "2019",
            tipe: "VELOZ",
            mesin: "1500",
            transmisi: "Manual",
            harga: 155000000,
          },
          {
            tahun: "2019",
            tipe: "VELOZ",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 160000000,
          },
        ],
      },
      {
        detail_merek: "RUSH",
        detail_spek: [
          {
            tahun: "2017",
            tipe: "G",
            mesin: "1500",
            transmisi: "Manual",
            harga: 150000000,
          },
          {
            tahun: "2017",
            tipe: "G",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 155000000,
          },
          {
            tahun: "2017",
            tipe: "S",
            mesin: "1500",
            transmisi: "Manual",
            harga: 160000000,
          },
          {
            tahun: "2017",
            tipe: "S",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 165000000,
          },
          {
            tahun: "2017",
            tipe: "TRD",
            mesin: "1500",
            transmisi: "Manual",
            harga: 170000000,
          },
          {
            tahun: "2017",
            tipe: "TRD",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 175000000,
          },
          {
            tahun: "2018",
            tipe: "G",
            mesin: "1500",
            transmisi: "Manual",
            harga: 155000000,
          },
          {
            tahun: "2018",
            tipe: "G",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 160000000,
          },
          {
            tahun: "2018",
            tipe: "TRD",
            mesin: "1500",
            transmisi: "Manual",
            harga: 175000000,
          },
          {
            tahun: "2018",
            tipe: "TRD",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 180000000,
          },
          {
            tahun: "2019",
            tipe: "G",
            mesin: "1500",
            transmisi: "Manual",
            harga: 165000000,
          },
          {
            tahun: "2019",
            tipe: "G",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 170000000,
          },
          {
            tahun: "2019",
            tipe: "TRD",
            mesin: "1500",
            transmisi: "Manual",
            harga: 18000000,
          },
          {
            tahun: "2019",
            tipe: "TRD",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 185000000,
          },
        ],
      },
    ],
  },
  {
    merek: "Honda",
    detail: [
      {
        detail_merek: "BRIO",
        detail_spek: [
          {
            tahun: "2017",
            tipe: "S",
            mesin: "1200",
            transmisi: "Manual",
            harga: 95000000,
          },
          {
            tahun: "2017",
            tipe: "S",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 100000000,
          },
          {
            tahun: "2017",
            tipe: "E",
            mesin: "1200",
            transmisi: "Manual",
            harga: 105000000,
          },
          {
            tahun: "2017",
            tipe: "E",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 110000000,
          },
          {
            tahun: "2017",
            tipe: "RS",
            mesin: "1200",
            transmisi: "Manual",
            harga: 115000000,
          },
          {
            tahun: "2017",
            tipe: "RS",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 120000000,
          },
          {
            tahun: "2018",
            tipe: "S",
            mesin: "1200",
            transmisi: "Manual",
            harga: 100000000,
          },
          {
            tahun: "2018",
            tipe: "S",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 105000000,
          },
          {
            tahun: "2018",
            tipe: "E",
            mesin: "1200",
            transmisi: "Manual",
            harga: 110000000,
          },
          {
            tahun: "2018",
            tipe: "E",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 115000000,
          },
          {
            tahun: "2018",
            tipe: "RS",
            mesin: "1200",
            transmisi: "Manual",
            harga: 120000000,
          },
          {
            tahun: "2018",
            tipe: "RS",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 125000000,
          },
          {
            tahun: "2019",
            tipe: "S",
            mesin: "1200",
            transmisi: "Manual",
            harga: 105000000,
          },
          {
            tahun: "2019",
            tipe: "S",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 110000000,
          },
          {
            tahun: "2019",
            tipe: "E",
            mesin: "1200",
            transmisi: "Manual",
            harga: 115000000,
          },
          {
            tahun: "2019",
            tipe: "E",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 120000000,
          },
          {
            tahun: "2019",
            tipe: "RS",
            mesin: "1200",
            transmisi: "Manual",
            harga: 125000000,
          },
          {
            tahun: "2019",
            tipe: "RS",
            mesin: "1200",
            transmisi: "Automatic",
            harga: 130000000,
          },
        ],
      },
      {
        detail_merek: "BRV",
        detail_spek: [
          {
            tahun: "2017",
            tipe: "S",
            mesin: "1500",
            transmisi: "Manual",
            harga: 135000000,
          },
          {
            tahun: "2017",
            tipe: "E",
            mesin: "1500",
            transmisi: "Manual",
            harga: 140000000,
          },
          {
            tahun: "2017",
            tipe: "E",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 145000000,
          },
          {
            tahun: "2017",
            tipe: "PRESTIGE",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 155000000,
          },
          {
            tahun: "2018",
            tipe: "S",
            mesin: "1500",
            transmisi: "Manual",
            harga: 140000000,
          },
          {
            tahun: "2018",
            tipe: "E",
            mesin: "1500",
            transmisi: "Manual",
            harga: 145000000,
          },
          {
            tahun: "2018",
            tipe: "E",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 150000000,
          },
          {
            tahun: "2018",
            tipe: "PRESTIGE",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 165000000,
          },
          {
            tahun: "2019",
            tipe: "S",
            mesin: "1500",
            transmisi: "Manual",
            harga: 145000000,
          },
          {
            tahun: "2019",
            tipe: "E",
            mesin: "1500",
            transmisi: "Manual",
            harga: 150000000,
          },
          {
            tahun: "2019",
            tipe: "E",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 155000000,
          },
          {
            tahun: "2019",
            tipe: "PRESTIGE",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 175000000,
          },
        ],
      },
      {
        detail_merek: "HRV",
        detail_spek: [
          {
            tahun: "2017",
            tipe: "S",
            mesin: "1500",
            transmisi: "Manual",
            harga: 180000000,
          },
          {
            tahun: "2017",
            tipe: "S",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 185000000,
          },
          {
            tahun: "2017",
            tipe: "E",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 210000000,
          },
          {
            tahun: "2017",
            tipe: "E",
            mesin: "1800",
            transmisi: "Automatic",
            harga: 225000000,
          },
          {
            tahun: "2017",
            tipe: "PRESTIGE",
            mesin: "1800",
            transmisi: "Automatic",
            harga: 250000000,
          },
          {
            tahun: "2018",
            tipe: "S",
            mesin: "1500",
            transmisi: "Manual",
            harga: 185000000,
          },
          {
            tahun: "2018",
            tipe: "S",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 190000000,
          },
          {
            tahun: "2018",
            tipe: "E",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 220000000,
          },
          {
            tahun: "2018",
            tipe: "E",
            mesin: "1800",
            transmisi: "Automatic",
            harga: 230000000,
          },
          {
            tahun: "2018",
            tipe: "PRESTIGE",
            mesin: "1800",
            transmisi: "Automatic",
            harga: 265000000,
          },
          {
            tahun: "2019",
            tipe: "S",
            mesin: "1500",
            transmisi: "Manual",
            harga: 190000000,
          },
          {
            tahun: "2019",
            tipe: "S",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 195000000,
          },
          {
            tahun: "2019",
            tipe: "E",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 230000000,
          },
          {
            tahun: "2019",
            tipe: "E",
            mesin: "1800",
            transmisi: "Automatic",
            harga: 240000000,
          },
          {
            tahun: "2019",
            tipe: "PRESTIGE",
            mesin: "1800",
            transmisi: "Automatic",
            harga: 275000000,
          },
        ],
      },
    ],
  },
  {
    merek: "Mitsubishi",
    detail: [
      {
        detail_merek: "XPANDER",
        detail_spek: [
          {
            tahun: "2017",
            tipe: "GLS",
            mesin: "1500",
            transmisi: "Manual",
            harga: 130000000,
          },
          {
            tahun: "2017",
            tipe: "EXCEED",
            mesin: "1500",
            transmisi: "Manual",
            harga: 140000000,
          },
          {
            tahun: "2017",
            tipe: "EXCEED",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 145000000,
          },
          {
            tahun: "2017",
            tipe: "SPORT",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 160000000,
          },
          {
            tahun: "2017",
            tipe: "ULTIMATE",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 165000000,
          },
          {
            tahun: "2018",
            tipe: "GLS",
            mesin: "1500",
            transmisi: "Manual",
            harga: 140000000,
          },
          {
            tahun: "2018",
            tipe: "EXCEED",
            mesin: "1500",
            transmisi: "Manual",
            harga: 150000000,
          },
          {
            tahun: "2018",
            tipe: "EXCEED",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 155000000,
          },
          {
            tahun: "2018",
            tipe: "SPORT",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 170000000,
          },
          {
            tahun: "2018",
            tipe: "ULTIMATE",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 175000000,
          },
          {
            tahun: "2019",
            tipe: "GLS",
            mesin: "1500",
            transmisi: "Manual",
            harga: 150000000,
          },
          {
            tahun: "2019",
            tipe: "EXCEED",
            mesin: "1500",
            transmisi: "Manual",
            harga: 160000000,
          },
          {
            tahun: "2019",
            tipe: "EXCEED",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 165000000,
          },
          {
            tahun: "2019",
            tipe: "SPORT",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 180000000,
          },
          {
            tahun: "2019",
            tipe: "ULTIMATE",
            mesin: "1500",
            transmisi: "Automatic",
            harga: 190000000,
          },
        ],
      },
      {
        detail_merek: "OUTLANDER SPORT",
        detail_spek: [
          {
            tahun: "2017",
            tipe: "GLS",
            mesin: "2000",
            transmisi: "Automatic",
            harga: 160000000,
          },
          {
            tahun: "2017",
            tipe: "GLX",
            mesin: "2000",
            transmisi: "Manual",
            harga: 160000000,
          },
          {
            tahun: "2017",
            tipe: "PX",
            mesin: "2000",
            transmisi: "Automatic",
            harga: 210000000,
          },
          {
            tahun: "2018",
            tipe: "GLS",
            mesin: "2000",
            transmisi: "Automatic",
            harga: 170000000,
          },
          {
            tahun: "2018",
            tipe: "GLX",
            mesin: "2000",
            transmisi: "Manual",
            harga: 170000000,
          },
          {
            tahun: "2018",
            tipe: "PX",
            mesin: "2000",
            transmisi: "Automatic",
            harga: 220000000,
          },
        ],
      },
      {
        detail_merek: "PAJERO SPORT",
        detail_spek: [
          {
            tahun: "2017",
            tipe: "EXCEED",
            mesin: "2500",
            transmisi: "Automatic",
            harga: 380000000,
          },
          {
            tahun: "2017",
            tipe: "DAKAR ULTIMATE",
            mesin: "2500",
            transmisi: "Automatic",
            harga: 420000000,
          },
          {
            tahun: "2017",
            tipe: "DAKAR 4X2",
            mesin: "2500",
            transmisi: "Automatic",
            harga: 420000000,
          },
          {
            tahun: "2017",
            tipe: "DAKAR 4X4",
            mesin: "2500",
            transmisi: "Automatic",
            harga: 500000000,
          },
          {
            tahun: "2018",
            tipe: "EXCEED",
            mesin: "2500",
            transmisi: "Manual",
            harga: 400000000,
          },
          {
            tahun: "2018",
            tipe: "EXCEED",
            mesin: "2500",
            transmisi: "Automatic",
            harga: 405000000,
          },
          {
            tahun: "2018",
            tipe: "DAKAR ULTIMATE",
            mesin: "2500",
            transmisi: "Automatic",
            harga: 450000000,
          },
          {
            tahun: "2018",
            tipe: "DAKAR 4X2",
            mesin: "2500",
            transmisi: "Automatic",
            harga: 500000000,
          },
          {
            tahun: "2018",
            tipe: "DAKAR 4X4",
            mesin: "2500",
            transmisi: "Automatic",
            harga: 550000000,
          },
          {
            tahun: "2019",
            tipe: "EXCEED",
            mesin: "2500",
            transmisi: "Manual",
            harga: 420000000,
          },
          {
            tahun: "2019",
            tipe: "EXCEED",
            mesin: "2500",
            transmisi: "Automatic",
            harga: 425000000,
          },
          {
            tahun: "2019",
            tipe: "DAKAR ULTIMATE",
            mesin: "2500",
            transmisi: "Automatic",
            harga: 480000000,
          },
          {
            tahun: "2019",
            tipe: "DAKAR 4X2",
            mesin: "2500",
            transmisi: "Automatic",
            harga: 510000000,
          },
          {
            tahun: "2019",
            tipe: "DAKAR 4X4",
            mesin: "2500",
            transmisi: "Automatic",
            harga: 600000000,
          },
        ],
      },
    ],
  },
];
